name: Lint and build all NX projects

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i
      - run: npx nx run-many -t build
